openapi: 3.0.3
info:
  title: Django DRF Ecomerce
  version: 0.0.0
paths:
  /api/category/:
    get:
      operationId: api_category_retrieve
      description: A simple viewset for viewing all the categories
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
