# Generated by Django 5.1.1 on 2024-09-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
